General:
    roi: POLYGON ((48.0 11.3, 48.2 11.300, 48.1 11.1, 48.0 11, 48.0 11.3))
    start_time: 2017-01-01
    end_time: 2017-12-31
    time_interval: 1 # 1 day
    spatial_resolution : 10 # metres
    state_mask: /path/to/my/state_mask.tif # Or shape?
    output_directory_root: /some/where/
    # output_prefix: my_test_33	

Inference: # inference config
    - parameters:
        - LAI
        - soil_moisture
    - optical_operator_library: some_operator.nc   # Optional
    - sar_operator_library: some_other_operator.nc # Optional
    - a: identity
    - inflation: 1e3

Prior:
  priors:
    - sm_clim
    # - sm_recent
    # - veg_pft
  sm:
    sm_clim:
      type: climatology
      climatology_file: ../aux_data/CCI_SM_climatology_eur_merged_inv.nc
    # sm_recent:
    #       type: recent
    # sm_static:
    #       type: static
    # sm_dynamic:
    #     type: dynamic
    #     model:
    #         - API
    #         - other
  # veg:
    # veg_pft:
    #   type: pft
    #   database: /aux_data/some_DB
    # veg_spec:
    #   type: species
    #   database: /user_data/some_DB
    # - 
